# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 02:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20180213_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 3, 43, 56, 104387, tzinfo=utc))),
                ('accepted', models.ManyToManyField(null=True, related_name='accepted', to='user.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_type', to='event.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='super_invited',
            field=models.ManyToManyField(null=True, related_name='super_invited', to='user.User'),
        ),
    ]
