# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 0, 5, 55, 867927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
