# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180403_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 8, 39, 0, 263119, tzinfo=utc)),
        ),
    ]
