# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180405_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 8, 9, 49, 936079, tzinfo=utc)),
        ),
    ]
