# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
