# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180319_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
